#!/bin/sh

#while [ "$z" != "0" ]
#do
	echo -e "Input peak time(whhmm): \c" #-e 
	read x
	echo -e "Input off-peak time(whhmm): \c" #-e
	read y

	shedule $x $y 
#	usage &
	#sleep_time $x $y &
	#sh sleep_time $x $y

#done


