#!/bin/sh

while [ "$z" != "0" ]
do
	echo -e "Input peak time(wddmm): \c" #-e 
	read x
	echo -e "Input off-peak time: \c" #-e
	read y
	echo -e "If you want to leave, please input 0 : \c" #-e
	read z

	nohup sh tm $x $y & 

done


